// frontend/src/api/stats.ts
import {
  GetNBackSessionStats,
  GetNumberPressingSessionStats,
  GetRpsSessionStats,
  GetShapeRotationSessionStats,
} from '@wails/go/main/App'; // Assuming these are generated by Wails

// --- RPS Stats Interfaces ---
export interface RpsProblemCardHolderStat {
  problemCardHolder: string;
  totalQuestions: number;
  totalCorrect: number;
  accuracy: number;
  averageResponseTimeMs: number;
}

export interface RpsRoundStats {
  round: number;
  totalQuestions: number;
  totalCorrect: number;
  accuracy: number;
  averageResponseTimeMs: number;
  problemCardHolderStats: RpsProblemCardHolderStat[];
}

export interface RpsSessionStats {
  sessionId: number;
  totalQuestions: number;
  totalCorrect: number;
  overallAccuracy: number;
  averageResponseTimeMs: number;
  roundStats: RpsRoundStats[];
}

export async function fetchRpsSessionStats(sessionId: number): Promise<RpsSessionStats> {
  return GetRpsSessionStats(sessionId);
}

// --- Shape Rotation Stats Interfaces ---
export interface ShapeRotationRoundStats {
  round: number;
  totalQuestions: number;
  totalCorrect: number;
  accuracy: number;
  averageSolveTimeMs: number;
  averageClickCount: number;
}

export interface ShapeRotationSessionStats {
  sessionId: number;
  totalQuestions: number;
  totalCorrect: number;
  overallAccuracy: number;
  averageSolveTimeMs: number;
  averageClickCount: number;
  roundStats: ShapeRotationRoundStats[];
}

export async function fetchShapeRotationSessionStats(sessionId: number): Promise<ShapeRotationSessionStats> {
  return GetShapeRotationSessionStats(sessionId);
}

// --- Number Pressing Stats Interfaces ---
export interface NumberPressingConditionStat {
  conditionType: string;
  totalQuestions: number;
  totalCorrect: number;
  accuracy: number;
  averageTimeTakenSec: number;
}

export interface NumberPressingRoundStats {
  round: number;
  totalQuestions: number;
  totalCorrect: number;
  accuracy: number;
  averageTimeTakenSec: number;
  conditionStats?: NumberPressingConditionStat[]; // Optional for R1
}

export interface NumberPressingSessionStats {
  sessionId: number;
  totalQuestions: number;
  totalCorrect: number;
  overallAccuracy: number;
  averageTimeTakenSec: number;
  roundStats: NumberPressingRoundStats[];
}

export async function fetchNumberPressingSessionStats(sessionId: number): Promise<NumberPressingSessionStats> {
  return GetNumberPressingSessionStats(sessionId);
}

// --- N-Back Stats Interfaces ---
export interface NBackLevelStat {
  nBackLevel: number;
  totalQuestions: number;
  totalCorrect: number;
  accuracy: number;
  averageResponseTimeMs: number;
}

export interface NBackRoundStats {
  round: number;
  totalQuestions: number;
  totalCorrect: number;
  accuracy: number;
  averageResponseTimeMs: number;
  nBackLevelStats?: NBackLevelStat[]; // Optional for R1
}

export interface NBackSessionStats {
  sessionId: number;
  totalQuestions: number;
  totalCorrect: number;
  overallAccuracy: number;
  averageResponseTimeMs: number;
  roundStats: NBackRoundStats[];
}

export async function fetchNBackSessionStats(sessionId: number): Promise<NBackSessionStats> {
  return GetNBackSessionStats(sessionId);
}
