// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateCorrectClicksR2(arg1) {
  return window['go']['main']['App']['CalculateCorrectClicksR2'](arg1);
}

export function GetPaginatedNBackSessionsWithResults(arg1, arg2) {
  return window['go']['main']['App']['GetPaginatedNBackSessionsWithResults'](arg1, arg2);
}

export function GetPaginatedNumberPressingSessionsWithResults(arg1, arg2) {
  return window['go']['main']['App']['GetPaginatedNumberPressingSessionsWithResults'](arg1, arg2);
}

export function GetPaginatedRpsSessionsWithResults(arg1, arg2) {
  return window['go']['main']['App']['GetPaginatedRpsSessionsWithResults'](arg1, arg2);
}

export function GetPaginatedShapeRotationSessionsWithResults(arg1, arg2) {
  return window['go']['main']['App']['GetPaginatedShapeRotationSessionsWithResults'](arg1, arg2);
}

export function GetSessionResults(arg1, arg2) {
  return window['go']['main']['App']['GetSessionResults'](arg1, arg2);
}

export function GetShapeGroups() {
  return window['go']['main']['App']['GetShapeGroups']();
}

export function GetShapeRotationProblems(arg1, arg2) {
  return window['go']['main']['App']['GetShapeRotationProblems'](arg1, arg2);
}

export function SaveShapeRotationSession(arg1) {
  return window['go']['main']['App']['SaveShapeRotationSession'](arg1);
}

export function StartNBackGame(arg1) {
  return window['go']['main']['App']['StartNBackGame'](arg1);
}

export function StartNumberPressingGame(arg1) {
  return window['go']['main']['App']['StartNumberPressingGame'](arg1);
}

export function StartRpsGame(arg1) {
  return window['go']['main']['App']['StartRpsGame'](arg1);
}

export function SubmitNBackAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitNBackAnswer'](arg1, arg2, arg3);
}

export function SubmitNumberPressingResultR1(arg1) {
  return window['go']['main']['App']['SubmitNumberPressingResultR1'](arg1);
}

export function SubmitNumberPressingResultR2(arg1) {
  return window['go']['main']['App']['SubmitNumberPressingResultR2'](arg1);
}

export function SubmitRpsAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitRpsAnswer'](arg1, arg2, arg3);
}

export function SubmitShapeRotationAnswerAsync(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SubmitShapeRotationAnswerAsync'](arg1, arg2, arg3, arg4, arg5);
}
