// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetShapeGroups() {
  return window['go']['main']['App']['GetShapeGroups']();
}

export function StartNBackGame(arg1) {
  return window['go']['main']['App']['StartNBackGame'](arg1);
}

export function SubmitNBackAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitNBackAnswer'](arg1, arg2, arg3);
}
