// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllNBackResults() {
  return window['go']['main']['App']['GetAllNBackResults']();
}

export function GetNBackGameSessions() {
  return window['go']['main']['App']['GetNBackGameSessions']();
}

export function GetNBackResultsForSession(arg1) {
  return window['go']['main']['App']['GetNBackResultsForSession'](arg1);
}

export function GetRpsGameSessions() {
  return window['go']['main']['App']['GetRpsGameSessions']();
}

export function GetRpsResultsForSession(arg1) {
  return window['go']['main']['App']['GetRpsResultsForSession'](arg1);
}

export function GetShapeGroups() {
  return window['go']['main']['App']['GetShapeGroups']();
}

export function StartNBackGame(arg1) {
  return window['go']['main']['App']['StartNBackGame'](arg1);
}

export function StartRpsGame(arg1) {
  return window['go']['main']['App']['StartRpsGame'](arg1);
}

export function SubmitNBackAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitNBackAnswer'](arg1, arg2, arg3);
}

export function SubmitRpsAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitRpsAnswer'](arg1, arg2, arg3);
}
