// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {shape_rotation} from '../models';
import {nback} from '../models';
import {rps} from '../models';

export function CalculateCorrectClicksR2(arg1:types.NumberPressingProblemR2):Promise<Array<number>>;

export function GetCountComparisonSessionStats(arg1:number):Promise<types.CountComparisonSessionStats>;

export function GetNBackSessionStats(arg1:number):Promise<types.NBackSessionStats>;

export function GetNextCountComparisonProblem():Promise<types.CountComparisonProblem>;

export function GetNumberPressingSessionStats(arg1:number):Promise<types.NumberPressingSessionStats>;

export function GetPaginatedCountComparisonSessionsWithResults(arg1:number,arg2:number):Promise<types.PaginatedCountComparisonSessions>;

export function GetPaginatedNBackSessionsWithResults(arg1:number,arg2:number):Promise<types.PaginatedNBackSessions>;

export function GetPaginatedNumberPressingSessionsWithResults(arg1:number,arg2:number):Promise<types.PaginatedNumberPressingSessions>;

export function GetPaginatedRpsSessionsWithResults(arg1:number,arg2:number):Promise<types.PaginatedRpsSessions>;

export function GetPaginatedShapeRotationSessionsWithResults(arg1:number,arg2:number):Promise<types.PaginatedShapeRotationSessions>;

export function GetRpsSessionStats(arg1:number):Promise<types.RpsSessionStats>;

export function GetSessionResults(arg1:string,arg2:number):Promise<string>;

export function GetShapeGroups():Promise<Record<string, Array<string>>>;

export function GetShapeRotationProblems(arg1:number,arg2:number):Promise<Array<shape_rotation.ShapeRotationProblemWithFinalShape>>;

export function GetShapeRotationSessionStats(arg1:number):Promise<types.ShapeRotationSessionStats>;

export function SaveShapeRotationSession(arg1:types.ShapeRotationSettings):Promise<number>;

export function StartCountComparisonGame(arg1:types.CountComparisonSettings):Promise<number>;

export function StartNBackGame(arg1:types.NBackSettings):Promise<nback.NBackGameState>;

export function StartNumberPressingGame(arg1:types.NumberPressingSetup):Promise<types.NumberPressingGameState>;

export function StartRpsGame(arg1:types.RpsSettings):Promise<rps.GameState>;

export function SubmitCountComparisonAnswer(arg1:types.CountComparisonSubmission):Promise<void>;

export function SubmitNBackAnswer(arg1:string,arg2:number,arg3:number):Promise<types.NBackResult>;

export function SubmitNumberPressingResultR1(arg1:types.NumberPressingResultR1):Promise<void>;

export function SubmitNumberPressingResultR2(arg1:types.NumberPressingResultR2):Promise<void>;

export function SubmitRpsAnswer(arg1:string,arg2:number,arg3:number):Promise<types.RpsResult>;

export function SubmitShapeRotationAnswerAsync(arg1:number,arg2:shape_rotation.ShapeRotationProblemWithFinalShape,arg3:Array<string>,arg4:number,arg5:number):Promise<void>;
